### ISSUE TITLE
uploading file using ajax

### ISSUE THREAD

**Issue by iktareen** [umr-ds/serval-tests#1]
Hello, I am trying to insert file in rhizome through ajax. But file is not uploading here is my code. 
        var data=new FormData();
	data.append("manifest","");
	data.append("payload",file);
	
	$.ajax
	({
	  type: "POST",
	  url: "http://localhost:4110/restful/rhizome/insert",
	  data:data,
	  processData: false,
      contentType:'rhizome/manifest; format=text+binarysig',
	  headers: {
		"Authorization": "Basic " + btoa(username + ":" + password)
	  }, 
	  success: function (data){
		console.log(data);
	  },
	  error:function(data){
		console.log("error"); 
	  }
	});

**Comment by adur1990** [comment]
Hi,

unfortunately, this repo is the wrong place for this question. We build our own Serval Web client (caution: maybe outdated). [There](https://github.com/umr-ds/serval-web/blob/master/static/js/serval_rhizome.js#L27) you can find working code.

Furthermore, we are not the maintainers of Serval, we just use it because it's a cool project with a lot of capabilities. If you have further, Serval specific question, please visit their [Google Groups page](https://groups.google.com/forum/#!forum/serval-project-developers) or the respective [Github repo](https://github.com/servalproject).

Thank you.

**Comment by iktareen** [comment]
thanks man your solution works . (Y)

**Comment by iktareen** [comment]
thanks man your solution works . (Y)
